### ISSUE TITLE
Crash CursorWindow.java - Could not allocate CursorWindow 

### ISSUE THREAD

**Issue by DevHilmi** [splitio/android-client#222]
This crash happens since we fully migrate our online config to Split.io SDK, is it possible because our apps are having so much config that the database on Split causing this error?

I see on code you have this query which queries all cached config :

`@Query("SELECT name, body, updated_at FROM splits")
    List<SplitEntity> getAll();`

is it possible if you add @Transation on that query https://developer.android.com/reference/androidx/room/Transaction?authuser=2 ? 

_"If the result of the query is fairly big, it is better to run it inside a transaction to receive a consistent result. Otherwise, if the query result does not fit into a single CursorWindow, the query result may be corrupted due to changes in the database in between cursor window swaps."_

Stack-trace 

```
Fatal Exception: android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0//databases/2a108jbd3qchur8ehofuhfgquOVOoASMity1TtqCXkbQnI7WOrG0YZ1K' of size 2097152 due to error -25.
       at android.database.CursorWindow.nativeCreate(CursorWindow.java)
       at android.database.CursorWindow.<init>(CursorWindow.java:139)
       at android.database.CursorWindow.<init>(CursorWindow.java:120)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:202)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
       at androidx.room.InvalidationTracker$1.DoublePoint(SourceFile:417)
       at androidx.room.InvalidationTracker$1.run(SourceFile:388)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
       
       
      .................
      
      Split-EventsManager-0
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:387)
       at io.split.android.client.events.SplitEventsManager.equals(SourceFile:150)
       at io.split.android.client.events.SplitEventsManager.run(SourceFile:144)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by chillaq** [comment]
Thanks @DevHilmi , I see a pull request for this issue, we will review it and get back to you.

**Comment by NicoZelaya** [comment]
Hi @DevHilmi !

Sorry to hear of your inconveniences. We tried different scenarios on few devices with very high amounts of Splits (22k+) stored in the DB, with and without dynamic configs and we couldn't repro this particular failure. 
We do get some messages that are similar but none of them was a Fatal/crash and the applications recovered by themselves, with or without the transaction code.

Nevertheless, as you pointed out that query could return a big result so using @transaction seems like the right thing to do. We've released an RC where we merged your PR that you can try if you want, with version 2.6.9-rc1.  Since we couldn't repro we can't say for certain it'll fix your problem but it would be great if you can give it a try and let us know, if it fixes the issue we'll release as a stable patch.

If you could share some more details around where are you instantiating the SDK factories (on a lifecycle hook, main thread or background thread) as well as the code/configs used, when and how are you destroying it if that's the case, and which other libraries and versions you have installed, it would be amazing. You can share this here or through support@split.io if that's best.
We'll try to replicate your environment to see if we can also repro to confirm the fix. If you prefer to do it over zoom, please reach out through support@split.io so we schedule one.

Again, my sincere apologies for the inconveniences, we're working to try and figure out why you're getting issues with the SQLite DB as our top priority in mobile. 

Best regards,
Nicolas.

**Comment by DevHilmi** [comment]
Hi @NicoZelaya 

Thank you for the detailed explanation for this issue and RC Release.

For the @transaction improvement we already try it out in our project but the issue is still happening.

For details _"instantiating the SDK factories (on a lifecycle hook, main thread or background thread) as well as the code/configs used, when and how are you destroying it if that's the case, and which other libraries and versions you have installed"_. I will consult our Internal team to provide that through email.

**Comment by dstyo** [comment]
Hi @NicoZelaya 

This issue still exists even though we have used @transaction. This issue only appears on os 10. I want to ask which version of androidTargetSdkVersion and androidCompileSdkVersion does this split use? and what version of room for this split? is it using the target API and compile 29? If so, should we add <application android: requestLegacyExternalStorage = "true" ...> for android Q?

**Comment by NicoZelaya** [comment]
Hi @dstyo!

Currently we have the following setup in the SDK:

- compileSdkVersion: `28`
- minSdkVersion: `15`
- targetSdkVersion: `28`
- Room version: `'2.2.2'`

But in the app we're using to run our automated tests, we override the targetSdkVersion with `29` and Room `'2.2.5'`.
 
I think this is not access related, but you're definitely welcome to try and see if that tag solves the problem for you. Sadly, given we couldn't repro properly yet, we can't say for certain either it'll help or not. 

Thank you for sharing it anyways! Really appreciated, any extra detail you could have to help us reproduce the issue would be amazing.

Best,
Nico.

**Comment by chillaq** [comment]
Hi Dwi, We released Android SDK 2.6.9 to fix this issue.

Thanks
Bilal

**Comment by dstyo** [comment]
Thanks Bilal will upgrade into Android SDK 2.6.9 today , thank you split team.
